[build-system]
requires = ["setuptools>=84.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[project]
name = "toolbox"
version = "1.0.0"
description = "Python scriptlets"
authors = [
    {name = "George Boukeas", email = "george.boukeas@canonical.com"},
]
requires-python = ">=3.10"
dependencies = [
    "packaging",
    "pyyaml",
    "pygithub",
    "fabric>=3.2.3",
]
[project.scripts]
wait-for-ssh = "toolbox.cli.wait_for_ssh:main"
wait-for-packages-complete = "toolbox.cli.wait_for_packages_complete:main"
wait-for-snap-changes = "toolbox.cli.wait_for_snap_changes:main"
watch-checkbox-agent = "toolbox.cli.watch_checkbox_agent:main"
install-checkbox-snaps = "toolbox.cli.install_checkbox_snaps:main"
install-checkbox-debs = "toolbox.cli.install_checkbox_debs:main"
ensure-kernel = "toolbox.cli.ensure_kernel:main"
ensure-stable-snaps = "toolbox.cli.ensure_stable_snaps:main"
setup_apt_cache_proxy = "toolbox.cli.setup_apt_cache_proxy:main"
# deprecated, used by the bash version of install_checkbox_snaps
snap_connections = "toolbox.snap_connections:main"

[project.optional-dependencies]
dev = ["pytest", "pytest-mock", "pytest-cov"]

[tool.coverage.report]
skip_covered = false
skip_empty = false
